"""empty message

Revision ID: 105e8160f56d
Revises: 33786fc68fa0
Create Date: 2013-11-01 10:45:53.434813

"""

# revision identifiers, used by Alembic.
revision = '105e8160f56d'
down_revision = '33786fc68fa0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.BigInteger(), nullable=True),
    sa.Column('end_time', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session')
    ### end Alembic commands ###
