"""Adding user-session backref

Revision ID: 114448e372ac
Revises: 105e8160f56d
Create Date: 2013-11-01 10:51:21.217121

"""

# revision identifiers, used by Alembic.
revision = '114448e372ac'
down_revision = '105e8160f56d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
