"""empty message

Revision ID: 18ee38db0807
Revises: 1b63e7340600
Create Date: 2013-10-31 17:08:41.964897

"""

# revision identifiers, used by Alembic.
revision = '18ee38db0807'
down_revision = '1b63e7340600'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screenshot', u'url')
    op.add_column('user', sa.Column('last_throttle_check', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('throttle_counter', sa.SmallInteger(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'throttle_counter')
    op.drop_column('user', 'last_throttle_check')
    op.add_column('screenshot', sa.Column(u'url', mysql.VARCHAR(length=256), nullable=True))
    ### end Alembic commands ###
