"""empty message

Revision ID: 1ace0afcd10
Revises: 5916aea4303a
Create Date: 2014-01-24 14:38:57.116288

"""

# revision identifiers, used by Alembic.
revision = '1ace0afcd10'
down_revision = '5916aea4303a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('description', sa.Unicode(length=4096), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'description')
    ### end Alembic commands ###
