"""empty message

Revision ID: 1fc883aac40b
Revises: 2cae2779a933
Create Date: 2013-12-04 13:05:13.354328

"""

# revision identifiers, used by Alembic.
revision = '1fc883aac40b'
down_revision = '2cae2779a933'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
