"""Renaming session time fields

Revision ID: 284849f31ba3
Revises: 114448e372ac
Create Date: 2013-11-05 18:07:29.939015

"""

# revision identifiers, used by Alembic.
revision = '284849f31ba3'
down_revision = '114448e372ac'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('end', sa.BigInteger(), nullable=True))
    op.add_column('session', sa.Column('start', sa.BigInteger(), nullable=True))
    op.drop_column('session', u'start_time')
    op.drop_column('session', u'end_time')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column(u'end_time', mysql.BIGINT(display_width=20), nullable=True))
    op.add_column('session', sa.Column(u'start_time', mysql.BIGINT(display_width=20), nullable=True))
    op.drop_column('session', 'start')
    op.drop_column('session', 'end')
    ### end Alembic commands ###
