"""empty message

Revision ID: 2850b5a26a20
Revises: 1c748b9ae3d1
Create Date: 2014-02-21 15:59:47.495158

"""

# revision identifiers, used by Alembic.
revision = '2850b5a26a20'
down_revision = '1c748b9ae3d1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
