"""empty message

Revision ID: 29367cc3eef8
Revises: 57dfac96d8c3
Create Date: 2013-10-30 02:04:38.617504

"""

# revision identifiers, used by Alembic.
revision = '29367cc3eef8'
down_revision = '57dfac96d8c3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screenshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('time', sa.BigInteger(), nullable=True),
    sa.Column('url', sa.Unicode(length=256), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('screenshot')
    ### end Alembic commands ###
