"""empty message

Revision ID: 32dd278f60f0
Revises: 29367cc3eef8
Create Date: 2013-10-30 02:05:40.196997

"""

# revision identifiers, used by Alembic.
revision = '32dd278f60f0'
down_revision = '29367cc3eef8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
