"""empty message

Revision ID: 3ce94fcc013e
Revises: 3a59543c2ad0
Create Date: 2013-11-06 19:35:31.967915

"""

# revision identifiers, used by Alembic.
revision = '3ce94fcc013e'
down_revision = '3a59543c2ad0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
