"""empty message

Revision ID: 557d03b2f29e
Revises: 2a4ad279340f
Create Date: 2014-01-14 18:55:52.175605

"""

# revision identifiers, used by Alembic.
revision = '557d03b2f29e'
down_revision = '2a4ad279340f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('session', sa.Column('width', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'width')
    op.drop_column('session', 'height')
    ### end Alembic commands ###
