"""empty message

Revision ID: 5916aea4303a
Revises: 4339be0037c0
Create Date: 2014-01-24 07:45:44.393821

"""

# revision identifiers, used by Alembic.
revision = '5916aea4303a'
down_revision = '4339be0037c0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_screenshot_time', 'screenshot', ['time'], unique=False)
    op.create_index('ix_screenshot_user', 'screenshot', ['user'], unique=False)
    op.create_index('ix_session_end', 'session', ['end'], unique=False)
    op.create_index('ix_session_start', 'session', ['start'], unique=False)
    op.create_index('ix_session_user', 'session', ['user'], unique=False)
    op.create_index('ix_session_view_secret', 'session_view', ['secret'], unique=True)
    op.create_index('ix_session_view_session', 'session_view', ['session'], unique=False)
    op.create_index('ix_session_view_shamer', 'session_view', ['shamer'], unique=False)
    op.create_index('ix_shamer_user', 'shamer', ['user'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    op.alter_column('session','height', server_default='450')
    op.alter_column('session','width', server_default='800')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email', 'user')
    op.drop_index('ix_shamer_user', 'shamer')
    op.drop_index('ix_session_view_shamer', 'session_view')
    op.drop_index('ix_session_view_session', 'session_view')
    op.drop_index('ix_session_view_secret', 'session_view')
    op.drop_index('ix_session_user', 'session')
    op.drop_index('ix_session_start', 'session')
    op.drop_index('ix_session_end', 'session')
    op.drop_index('ix_screenshot_user', 'screenshot')
    op.drop_index('ix_screenshot_time', 'screenshot')
    op.alter_column("session","height",server_default="768")
    op.alter_column("session","width",server_default="1024")
    ### end Alembic commands ###
