"""empty message

Revision ID: 62e7aa694d3
Revises: 3ce94fcc013e
Create Date: 2013-11-06 19:36:09.422747

"""

# revision identifiers, used by Alembic.
revision = '62e7aa694d3'
down_revision = '3ce94fcc013e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shamer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('email', sa.Unicode(length=512), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shamer')
    ### end Alembic commands ###
