"""remove expiration (converting from float to int)

Revision ID: 30acde32c77e
Revises: c4a11d9ab98
Create Date: 2013-09-10 19:03:29.094168

"""

# revision identifiers, used by Alembic.
revision = '30acde32c77e'
down_revision = 'c4a11d9ab98'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload_creds', u'expiration')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_creds', sa.Column(u'expiration', mysql.FLOAT(), nullable=True))
    ### end Alembic commands ###
