"""change datetime to epoch

Revision ID: 3634af22b86d
Revises: 29a2b5ea8244
Create Date: 2013-09-04 17:19:30.610498

"""

# revision identifiers, used by Alembic.
revision = '3634af22b86d'
down_revision = '29a2b5ea8244'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
