"""Added session status

Revision ID: 3d89c3ff4a5e
Revises: 43c8d7a9ce00
Create Date: 2013-08-20 20:06:38.583260

"""

# revision identifiers, used by Alembic.
revision = '3d89c3ff4a5e'
down_revision = '43c8d7a9ce00'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'role')
    op.drop_table(u'roles_users')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'roles_users',
    sa.Column(u'user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column(u'role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], [u'role.id'], name=u'roles_users_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'roles_users_ibfk_2'),
    sa.PrimaryKeyConstraint(),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table(u'role',
    sa.Column(u'id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column(u'name', mysql.VARCHAR(length=80), nullable=True),
    sa.Column(u'description', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint(u'id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
