"""Add status to sessions

Revision ID: 19958bde13a0
Revises: 3b224a2f7704
Create Date: 2013-08-08 15:24:13.044927

"""

# revision identifiers, used by Alembic.
revision = '19958bde13a0'
down_revision = '3b224a2f7704'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('status', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'status')
    ### end Alembic commands ###
