"""remove expiration

Revision ID: 2048a94d4105
Revises: 21961f09b032
Create Date: 2013-09-04 17:21:21.213658

"""

# revision identifiers, used by Alembic.
revision = '2048a94d4105'
down_revision = '21961f09b032'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload_creds', u'expiration')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_creds', sa.Column(u'expiration', sa.DATETIME(), nullable=True))
    ### end Alembic commands ###
