"""tweaking

Revision ID: 536f3e3ba326
Revises: df7331a2aab
Create Date: 2013-08-08 16:07:45.383894

"""

# revision identifiers, used by Alembic.
revision = '536f3e3ba326'
down_revision = 'df7331a2aab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
