- hosts: staging
  user: ubuntu
  sudo: True

  vars:
    app_name: powershame
    repo_url: git@bitbucket.org:jaibot/powershame-site.git
    repo_remote: bb
    repo_version: dev
    webapps_dir: /opt/
    server_name: www.powershame.com staging.powershame.com
    user: ubuntu

  tasks:
    - name: ensure log directory
      action: file dest=${webapps_dir}/${app_name}/log state=directory

    - name: deploy code from repository
      action: git repo=$repo_url dest=${webapps_dir}/${app_name}/src remote=$repo_remote version=$repo_version

    - name: set config file
      copy: src=../config.py dest={{ webapps_dir }}/{{ app_name }}/config.py

    - name: install dependencies into virtualenv
      action: pip requirements=${webapps_dir}/${app_name}/src/requirements.txt virtualenv=${webapps_dir}/${app_name}/venv state=present

    - name: create supervisor program config
      action: template src=files/templates/supervisor-site.ini dest=/etc/supervisor/${app_name}.ini
      notify:
        - restart app

    - name: create nginx site config
      action: template src=files/templates/nginx_site.conf dest=/etc/nginx/sites-available/${app_name}.conf
      notify:
        - restart nginx

    - name: create gunicorn config file
      action: template src=files/templates/gunicorn.py dest={{webapps_dir }}/{{ app_name }}/gunicorn.py owner={{ user }} mode=0600

    - name: link nginx config
      action: file src=/etc/nginx/sites-available/${app_name}.conf dest=/etc/nginx/sites-enabled/${app_name}.conf state=link

    - name: start app
      action: supervisorctl name={{ app_name }} state=started

    - name: start nginx
      action: service name=nginx state=started

  handlers:
    - name: restart app
      action: supervisorctl name={{ app_name }} state=restarted

    - name: restart nginx
      action: service name=nginx state=restarted
