"""change datetime to epoch

Revision ID: 21961f09b032
Revises: 3634af22b86d
Create Date: 2013-09-04 17:19:52.293979

"""

# revision identifiers, used by Alembic.
revision = '21961f09b032'
down_revision = '3634af22b86d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
