"""index usernamed

Revision ID: 291c1b6e962d
Revises: 52ca476174d8
Create Date: 2013-08-08 11:59:31.600301

"""

# revision identifiers, used by Alembic.
revision = '291c1b6e962d'
down_revision = '52ca476174d8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shamers',
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('shamer', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shamer'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user', 'shamer')
    )
    op.drop_table(u'account')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'account',
    sa.Column(u'id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column(u'name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column(u'description', mysql.VARCHAR(length=200), nullable=True),
    sa.Column(u'coolness', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint(u'id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('shamers')
    ### end Alembic commands ###
