"""empty message

Revision ID: 2cae2779a933
Revises: 2e40add1d717
Create Date: 2013-11-13 21:37:03.296763

"""

# revision identifiers, used by Alembic.
revision = '2cae2779a933'
down_revision = '2e40add1d717'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'test')
    op.add_column('session', sa.Column('bucket', sa.Unicode(length=64), nullable=True))
    op.add_column('session', sa.Column('key', sa.Unicode(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'key')
    op.drop_column('session', 'bucket')
    op.create_table(u'test',
    sa.Column(u'testvar', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint(u'testvar', name=u'test_pkey')
    )
    ### end Alembic commands ###
