"""empty message

Revision ID: 2e40add1d717
Revises: 318f16b6da32
Create Date: 2013-11-10 20:10:43.753640

"""

# revision identifiers, used by Alembic.
revision = '2e40add1d717'
down_revision = '318f16b6da32'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('secret', sa.Unicode(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'secret')
    ### end Alembic commands ###
