"""empty message

Revision ID: 33786fc68fa0
Revises: 18ee38db0807
Create Date: 2013-11-01 10:36:17.378341

"""

# revision identifiers, used by Alembic.
revision = '33786fc68fa0'
down_revision = '18ee38db0807'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
