"""empty message

Revision ID: 3a59543c2ad0
Revises: 284849f31ba3
Create Date: 2013-11-06 19:13:07.806504

"""

# revision identifiers, used by Alembic.
revision = '3a59543c2ad0'
down_revision = '284849f31ba3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('rendered', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'rendered')
    ### end Alembic commands ###
