"""Upgrading alembic, testing new detection

Revision ID: 2bb14001b2b9
Revises: 5524572b9f16
Create Date: 2013-10-28 15:07:20.857341

"""

# revision identifiers, used by Alembic.
revision = '2bb14001b2b9'
down_revision = '5524572b9f16'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
