"""Starting from scratch

Revision ID: 3943077a8823
Revises: None
Create Date: 2013-09-24 18:21:32.500721

"""

# revision identifiers, used by Alembic.
revision = '3943077a8823'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Unicode(length=32), nullable=True),
    sa.Column('password', sa.Unicode(length=130), nullable=True),
    sa.Column('is_registered', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upload_creds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('expiration', sa.BigInteger(), nullable=True),
    sa.Column('access_id', sa.String(length=256), nullable=True),
    sa.Column('secret_key', sa.String(length=256), nullable=True),
    sa.Column('session_token', sa.String(length=2048), nullable=True),
    sa.Column('prefix', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=256), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('valid', sa.Boolean(), nullable=True),
    sa.Column('date_authorized', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('contact_type', sa.SmallInteger(), nullable=True),
    sa.Column('identifier', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shamers',
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('shamer', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shamer'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user', 'shamer')
    )
    op.create_table('user_shamers',
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('shamer', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shamer'], ['contact_info.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint()
    )
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=256), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('source', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('url', sa.Unicode(length=2048), nullable=True),
    sa.Column('url_expire', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source'], ['client.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_shamers',
    sa.Column('session', sa.Integer(), nullable=True),
    sa.Column('shamer', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session'], ['session.id'], ),
    sa.ForeignKeyConstraint(['shamer'], ['contact_info.id'], ),
    sa.PrimaryKeyConstraint()
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_shamers')
    op.drop_table('session')
    op.drop_table('user_shamers')
    op.drop_table('shamers')
    op.drop_table('contact_info')
    op.drop_table('client')
    op.drop_table('upload_creds')
    op.drop_table('user')
    ### end Alembic commands ###
