"""upload system now using signed urls instead of federated tokens

Revision ID: 3e9c087d5cf3
Revises: a1a394a7396
Create Date: 2013-10-14 23:47:58.429400

"""

# revision identifiers, used by Alembic.
revision = '3e9c087d5cf3'
down_revision = 'a1a394a7396'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('date_issued', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table(u'upload_creds')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'upload_creds',
    sa.Column(u'id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column(u'user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user'], [u'user.id'], name=u'upload_creds_ibfk_1'),
    sa.PrimaryKeyConstraint(u'id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('upload_form')
    ### end Alembic commands ###
