"""Testing with compare_type

Revision ID: 418ea52a4658
Revises: 4ae43052a766
Create Date: 2013-10-28 16:32:10.680874

"""

# revision identifiers, used by Alembic.
revision = '418ea52a4658'
down_revision = '4ae43052a766'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=130),
               type_=sa.Unicode(length=255),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.Unicode(length=255),
               type_=mysql.VARCHAR(length=130),
               existing_nullable=True)
    op.alter_column('user', 'active',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    ### end Alembic commands ###
