"""Expanding password field

Revision ID: 4ae43052a766
Revises: 2bb14001b2b9
Create Date: 2013-10-28 16:26:26.931255

"""

# revision identifiers, used by Alembic.
revision = '4ae43052a766'
down_revision = '2bb14001b2b9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
