"""Rebuilding with a sane API

Revision ID: 5524572b9f16
Revises: 3e9c087d5cf3
Create Date: 2013-10-28 14:41:40.385791

"""

# revision identifiers, used by Alembic.
revision = '5524572b9f16'
down_revision = '3e9c087d5cf3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint()
    )
    op.drop_table(u'upload_form')
    op.drop_table(u'session')
    op.drop_table(u'user_shamers')
    op.drop_table(u'shamers')
    op.drop_table(u'client')
    op.drop_table(u'contact_info')
    op.add_column('user', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('email', sa.String(length=255), nullable=True))
    op.drop_column('user', u'is_registered')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column(u'is_registered', mysql.TINYINT(display_width=1), nullable=True))
    op.drop_column('user', 'email')
    op.drop_column('user', 'confirmed_at')
    op.drop_column('user', 'active')
    op.create_table(u'contact_info',
    sa.Column(u'id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column(u'user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column(u'contact_type', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column(u'identifier', mysql.VARCHAR(length=512), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'contact_info_ibfk_1'),
    sa.PrimaryKeyConstraint(u'id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table(u'client',
    sa.Column(u'id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column(u'token', mysql.VARCHAR(length=256), nullable=True),
    sa.Column(u'user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column(u'name', mysql.VARCHAR(length=256), nullable=True),
    sa.Column(u'valid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column(u'date_authorized', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user'], [u'user.id'], name=u'client_ibfk_1'),
    sa.PrimaryKeyConstraint(u'id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table(u'shamers',
    sa.Column(u'user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column(u'shamer', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['shamer'], [u'user.id'], name=u'shamers_ibfk_1'),
    sa.ForeignKeyConstraint(['user'], [u'user.id'], name=u'shamers_ibfk_2'),
    sa.PrimaryKeyConstraint(u'user', u'shamer'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table(u'user_shamers',
    sa.Column(u'user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column(u'shamer', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['shamer'], [u'contact_info.id'], name=u'user_shamers_ibfk_1'),
    sa.ForeignKeyConstraint(['user'], [u'user.id'], name=u'user_shamers_ibfk_2'),
    sa.PrimaryKeyConstraint(),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table(u'session',
    sa.Column(u'id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column(u'name', mysql.VARCHAR(length=256), nullable=True),
    sa.Column(u'user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column(u'source', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column(u'status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column(u'start_time', sa.DATETIME(), nullable=True),
    sa.Column(u'end_time', sa.DATETIME(), nullable=True),
    sa.Column(u'url', mysql.VARCHAR(length=2048), nullable=True),
    sa.Column(u'url_expire', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['source'], [u'client.id'], name=u'session_ibfk_1'),
    sa.ForeignKeyConstraint(['user'], [u'user.id'], name=u'session_ibfk_2'),
    sa.PrimaryKeyConstraint(u'id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table(u'upload_form',
    sa.Column(u'id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column(u'user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column(u'date_issued', mysql.TIME(), nullable=True),
    sa.ForeignKeyConstraint(['user'], [u'user.id'], name=u'upload_form_ibfk_1'),
    sa.PrimaryKeyConstraint(u'id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('roles_users')
    op.drop_table('role')
    ### end Alembic commands ###
