"""changed shot datetime to bigint(epoch)

Revision ID: 5a89c59d2ba3
Revises: 7b1fd7eeb0f
Create Date: 2013-10-29 12:48:42.126246

"""

# revision identifiers, used by Alembic.
revision = '5a89c59d2ba3'
down_revision = '7b1fd7eeb0f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'active',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    ### end Alembic commands ###
