"""changed username to email

Revision ID: 7b1fd7eeb0f
Revises: 51fad3bb2814
Create Date: 2013-10-28 18:29:39.353515

"""

# revision identifiers, used by Alembic.
revision = '7b1fd7eeb0f'
down_revision = '51fad3bb2814'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'role')
    op.drop_column('user', u'username')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column(u'username', mysql.VARCHAR(length=32), nullable=True))
    op.create_table(u'role',
    sa.Column(u'id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column(u'name', mysql.VARCHAR(length=80), nullable=True),
    sa.Column(u'description', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint(u'id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
