"""upload system now using signed urls instead of federated tokens

Revision ID: a1a394a7396
Revises: 4bf5bdfeda5
Create Date: 2013-10-14 21:02:04.881954

"""

# revision identifiers, used by Alembic.
revision = 'a1a394a7396'
down_revision = '4bf5bdfeda5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload_creds', u'secret_key')
    op.drop_column('upload_creds', u'prefix')
    op.drop_column('upload_creds', u'access_id')
    op.drop_column('upload_creds', u'expiration')
    op.drop_column('upload_creds', u'session_token')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_creds', sa.Column(u'session_token', mysql.VARCHAR(length=2048), nullable=True))
    op.add_column('upload_creds', sa.Column(u'expiration', mysql.BIGINT(display_width=20), nullable=True))
    op.add_column('upload_creds', sa.Column(u'access_id', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('upload_creds', sa.Column(u'prefix', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('upload_creds', sa.Column(u'secret_key', mysql.VARCHAR(length=256), nullable=True))
    ### end Alembic commands ###
