"""attempting to add screenshots

Revision ID: ee688821ba0
Revises: 5a89c59d2ba3
Create Date: 2013-10-30 01:52:06.156853

"""

# revision identifiers, used by Alembic.
revision = 'ee688821ba0'
down_revision = '5a89c59d2ba3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'active',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    ### end Alembic commands ###
